const aesthetics = [
    "90s themed",
    "anti-authority",
    "punk rock",
    "cottagecore",
    "grunge",
    "art deco",
    "avant-garde",
    "beatnik",
    "80's themed",
    "cyberpunk",
    "highly sarcastic",
    "british",
    "internally inconsistent",
    "gluten free",
    "vegan",
    "retro",
    "vintage",
    "free-range",
    "goth",
    "corporate",
    "VSCO",
    "normcore",
    "colorful",
    "ironic",
    "scary",
    "retro",
    "space themed",
    "SaaS",
]

export default aesthetics;