const projects = [
    "to do list",
    "weather app",
    "voting app",
    "chatbot",
    "INTERCAL interpreter",
    "home design app",
    "Twitter clone",
    "state sponsored surveillance daemon",
    "project idea generator app",
    "audio memo recorder",
    "calculator",
    "dice roller",
    "color pallete generator",
    "Jackbox game clone",
    "fractal generator app",
    "codenames game",
    "lava lamp simulator",
    "golf game",
    "space simulator game",
    "word processor",
    "vector design app",
    "calendar app",
    "mail client",
    "alarm clock app",
    "podcast app",
    "FORTRAN linter",
    "travel review app",
    "tiktok clone",
    "video call app",
    "messaging app",
    "food delivery app",
    "news app",
    "translation app",
    "lighter simulator app",
    "standards compliant web browser",
    "side project generator",
    "twitter clone",
    "covid tracker",
    "virtual enemy"
]

export default projects;